import cron from "node-cron";
import mongoose from "mongoose";
import axios from "axios";
import { sendDailyNewsletter } from "../utils/mailer";
import config from "../config/env";
import User from "../models/user.model";
import { ChatGroq } from "@langchain/groq";
import { SystemMessage, HumanMessage } from "@langchain/core/messages";

export const executeNewsletterAgent = async () => {
    console.log("⏰ Executing daily personalized newsletter logic...");

    try {
        // Find users who are verified to send them content
        const users = await User.find({});
        const db = mongoose.connection.db;
        if (!db) {
            console.error("DB connection not found during cron execute.");
            return;
        }

        const apiKey = config.GROQ_API_KEY.trim();
        if (!apiKey) {
            console.error("No GROQ_API_KEY setup for newsletter.");
            return;
        }

        const llm = new ChatGroq({
            apiKey: apiKey,
            model: "llama-3.3-70b-versatile",
            temperature: 0.6,
        });

        for (const user of users) {
            if (!user.email) continue;

            // Find latest startup generated by this user 
            const analysisDoc = await db.collection("analyses").findOne(
                { $or: [{ user_id: user.id }, { user_id: user._id.toString() }], type: "blueprint" },
                { sort: { _id: -1 } }
            );

            if (!analysisDoc || !analysisDoc.data) continue; // No business created yet

            const data = analysisDoc.data;
            const businessName = data.businessOverview?.name || "Your Startup";
            const industry = data.businessOverview?.industry || "Technology";

            // Determine if it's product based vs service based
            const isProductBased = JSON.stringify(data).toLowerCase().includes("product");

            let rawNewsContext = "No breaking news found for your industry today.";
            let rawProductsContext = "No specific product developments tracked today.";

            console.log(`Gathering intelligence for user ${user.email} holding business ${businessName}...`);

            // 1) Fetch News via NewsData
            if (config.NEWS_DATA_API_KEY) {
                try {
                    const query = encodeURIComponent(industry.split(" ")[0] || businessName);
                    const newsResp = await axios.get(`https://newsdata.io/api/1/latest?apikey=${config.NEWS_DATA_API_KEY}&q=${query}&language=en`);

                    if (newsResp.data && newsResp.data.results && newsResp.data.results.length > 0) {
                        const articles = newsResp.data.results.slice(0, 3).map((n: any) => `- **${n.title}**: ${n.description || n.content?.substring(0, 100) || "Read more."}`);
                        rawNewsContext = articles.join("\n\n");
                    }
                } catch (e: any) {
                    console.error(`News data fetch failed for ${businessName}:`, e.message);
                }
            }

            // 2) Fetch Product Intel via Open Web Ninja
            if (isProductBased && config.OPEN_WEB_NINJA_API_KEY) {
                try {
                    const query = encodeURIComponent(`new ${industry} products launched`);
                    const productResp = await axios.get(`https://api.openwebninja.com/v1/search?q=${query}`, {
                        headers: { "x-api-key": config.OPEN_WEB_NINJA_API_KEY }
                    });

                    if (productResp.data && productResp.data.organic_results) {
                        const products = productResp.data.organic_results.slice(0, 3).map((p: any) => `- [${p.title}](${p.link}): ${p.snippet}`);
                        rawProductsContext = products.join("\n\n");
                    }
                } catch (e: any) {
                    console.error(`Open Web Ninja fetch failed for ${businessName}:`, e.message);
                }
            }

            // 3) Generate Custom HTML Email with the Agent
            const prompt = `
You are the Startup Swarm Executive Assistant for "${businessName}", a growing business in the "${industry}" sector.
Your objective is to write an ultra-premium, beautifully styled daily HTML email newsletter tailored specifically for its founder.

Today's scoured news context (fetched live):
${rawNewsContext}

Today's scoured product releases/trends (fetched live):
${rawProductsContext}

Output ONLY valid, beautifully designed HTML formatting. DO NOT wrap with \`\`\`html or markdown blocks. Just raw HTML code.
Use sophisticated inline CSS like gradient backgrounds, soft borders, modern typography (Arial/San-Francisco), and shadows.
Make it look like a highly expensive consulting agency report!

Include:
1. Warm greeting.
2. Huge Header holding "Startup Swarm Intel - Daily Briefing".
3. A breakdown of the news and product data provided above, formatted cleanly (cards or lists) explaining why it matters to ${businessName}.
4. An actionable "Daily Mission" tailored to them.
5. End with the Startup Swarm Executive Agent signature.
`;

            try {
                const response = await llm.invoke([
                    new SystemMessage({ content: "You output only valid, stylized HTML. No explanations, no markdown wrappers." }),
                    new HumanMessage({ content: prompt })
                ]);

                let htmlContent = typeof response.content === "string" ? response.content : "";
                htmlContent = htmlContent.replace(/```html/gi, "").replace(/```/gi, "").trim();

                // 4) Fire the email!
                await sendDailyNewsletter(
                    user.email,
                    `Startup Swarm Intel: Daily Briefing for ${businessName}`,
                    htmlContent
                );

                console.log(`✅ Sent automated daily intel newsletter to ${user.email}`);

            } catch (emailErr: any) {
                console.error(`Failed to generate/send email agent to ${user.email}`, emailErr.message);
            }
        }

    } catch (error) {
        console.error("Cron massive failure:", error);
    }
};

export const startNewsletterCron = () => {
    // -------------------------------------------------------------
    // FOR TESTING:
    // Calling the function directly once below lets you test it!
    // executeNewsletterAgent();
    // -------------------------------------------------------------

    // Changing the cron to '* * * * *' runs it EVERY MINUTE for immediate testing
    // Change back to '0 8 * * *' when you are done testing to run 1x daily!
    cron.schedule("* * * * *", async () => {
        await executeNewsletterAgent();
    });

    console.log("📨 Autonomous Executive Email Agent scheduled (Running every minute for testing right now).");
};
